version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-intercambio
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intercambio_livros
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/script.sql:/docker-entrypoint-initdb.d/script.sql

volumes:
  mysql_data: